FLOAT=soft

CXXFLAGS		:= $(CFLAGS)
CPPFLAGS		:= $(CFLAGS)
CXXCP 			:= $(CXX) -E
CFLAGS			+= -pipe -mfloat-abi=$(FLOAT) -mcpu=arm1176jzf-s -fomit-frame-pointer -mabi=aapcs-linux -mtune=arm1176jzf-s -mfpu=vfp -Wno-psabi -mno-apcs-stack-check -O0 -mstructure-size-boundary=32 -mno-sched-prolog -g
LDFLAGS			+= -L/lib -L/usr/lib -L/opt/vc/lib/
INCLUDES		+= -isystem/usr/include -isystem/opt/vc/include -isystem/usr/include -isystem/opt/vc/include/interface/vcos/pthreads -isystem/usr/include/freetype2
